bot:
    token: # Your bot token here

servers:
    - server_1:
        id: # Your server ID here
        log_channel_id: # Your server log channel ID here

    - server_2:
        id: # Your server ID here
        log_channel_id: # Your server log channel ID here